export const skills = {
    frontEndSkills: [
        'CSS preprocessors',
        'SVG & animations',
        'White-labelling',
        'Web components',
        'React + Vite',
        'Storybook',
        'Tailwind',
        'Next.js',
        'Svelte',
        'Astro',
        'a11y',
        'msw',
        'UX',
        '*',
    ],
    backEndSkills: [
        'Serverless Framework',
        'Serverless Offline',
        'PostgreSQL',
        'DynamoDB',
        'Supabase',
        'GraphQL',
        'Node',
        'Go',
        '*',
    ],
    awsSkills: [
        'SecretsManager',
        'ParameterStore',
        'API Gateway',
        'CloudWatch',
        'CloudFront',
        'DynamoDB',
        'Cognito',
        'Amplify',
        'Lambda',
        'EC2',
        'S3',
        'λ',
    ],
    cicdSkills: [
        'Github Actions',
        'Optimizely',
        'BitBucket',
        'New Relic',
        'FullStory',
        'PagerDuty',
        'Jenkins',
        'GitLabs',
        'Jira',
        '*',
    ],
    tooling: [
        'Docker Compose',
        'JetBrains',
        'Vitest',
        'Codex',
        'Jest',
        'RTL',
        'Vim',
        '*',
    ],
    other: [
        'Video game industry, 10+ years',
        'YouTube channel',
        'gochenour CLI',
        'Ubuntu',
        'Elixir',
        '*',
    ],
};
